apiVersion: apps/v1
kind: Deployment
metadata:
  name: voting-app-deploy
  lables:
    name: voting-app-deploy
	app: demo-voting-app
spec:
  replicas: 1
  selector:
    matchlabes:
	  name: voting-app-pod
	  app: demo-voting-app
  template:
    metadata:
	  name: voting-app-pod
	  labels:
	    name: voting-app-pod
		app: demo-voting-app
	spec:
	  containers:
	    - name: voring-app
		  image: kodekloud/examplevotingapp_vote:v1
	      ports:
	        - containerPort: 80